// <auto-generated />
using System;
using MeetingMind.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeetingMind.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MeetingMindDbContext))]
    partial class MeetingMindDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeetingMind.Domain.Entities.MeetingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AutomaticRetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("AutomaticRetryLimit")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("HangfireJobId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OriginalFilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ProcessedFilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MeetingJobs");
                });

            modelBuilder.Entity("MeetingMind.Domain.Entities.MeetingMinutes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionItemsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullMinutesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MeetingJobId")
                        .HasColumnType("uuid");

                    b.Property<string>("MinutesFilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("NextStepsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RisksJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("MeetingJobId")
                        .IsUnique();

                    b.ToTable("MeetingMinutes");
                });

            modelBuilder.Entity("MeetingMind.Domain.Entities.MeetingTranscript", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MeetingJobId")
                        .HasColumnType("uuid");

                    b.Property<string>("TranscriptFilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("TranscriptText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MeetingJobId")
                        .IsUnique();

                    b.ToTable("MeetingTranscripts");
                });

            modelBuilder.Entity("MeetingMind.Domain.Entities.MeetingMinutes", b =>
                {
                    b.HasOne("MeetingMind.Domain.Entities.MeetingJob", "MeetingJob")
                        .WithOne("Minutes")
                        .HasForeignKey("MeetingMind.Domain.Entities.MeetingMinutes", "MeetingJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetingJob");
                });

            modelBuilder.Entity("MeetingMind.Domain.Entities.MeetingTranscript", b =>
                {
                    b.HasOne("MeetingMind.Domain.Entities.MeetingJob", "MeetingJob")
                        .WithOne("Transcript")
                        .HasForeignKey("MeetingMind.Domain.Entities.MeetingTranscript", "MeetingJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetingJob");
                });

            modelBuilder.Entity("MeetingMind.Domain.Entities.MeetingJob", b =>
                {
                    b.Navigation("Minutes");

                    b.Navigation("Transcript");
                });
#pragma warning restore 612, 618
        }
    }
}
